# Generated by Django 5.0.1 on 2024-01-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0004_movieinfo_directed_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='acted_by',
            field=models.ManyToManyField(null=True, related_name='acted_movies', to='firstApp.actor'),
        ),
    ]
