# Generated by Django 5.0.1 on 2024-01-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0005_actor_movieinfo_acted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='acted_by',
            field=models.ManyToManyField(related_name='acted_movies', to='firstApp.actor'),
        ),
    ]
